// Package main - classification engine.
//
// PRD section 6: deterministic, auditable, rules-based classification.
// NOT ML / heuristic-guessed. The Level 3 blocklist is hardcoded and must
// NEVER be bypassable from the UI (also re-checked in deleter.go).
package main

import (
	"path/filepath"
	"strings"
	"time"
)

// Level is the safety classification of a path.
type Level int

const (
	// LevelSafe = Level 1 - regenerable artifacts, safe to Clean.
	LevelSafe Level = 1
	// LevelReview = Level 2 - large but not 100% certain; Review or Archive.
	LevelReview Level = 2
	// LevelLocked = Level 3 - system/protected. No action button, ever.
	LevelLocked Level = 3
)

func (l Level) String() string {
	switch l {
	case LevelSafe:
		return "safe"
	case LevelReview:
		return "review"
	default:
		return "locked"
	}
}

// Action labels per PRD section 4/6.
var levelAction = map[Level]string{
	LevelSafe:   "Clean",
	LevelReview: "Review",
	LevelLocked: "", // no action, ever
}

// Action returns the allowed action label for the level.
func (l Level) Action() string { return levelAction[l] }

// -----------------------------------------------------------------------------
// Level 3 — hardcoded system blocklist (never bypassable)
// -----------------------------------------------------------------------------

var lockedPrefixes = []string{
	`c:\windows`,
	`c:\programdata`,
	`c:\program files`,
	`c:\program files (x86)`,
	`c:\users\default`,
}

// lockedNames are protected path components wherever they appear.
var lockedNames = []string{
	"system volume information",
	"$recycle.bin",
	"$windows.~bt",
	"$windows.~ws",
	"recovery",
	"boot",
	"pagefile.sys",
	"hiberfil.sys",
	"swapfile.sys",
	"dumpstack.log",
	"dumpstack.log.tmp",
}

// -----------------------------------------------------------------------------
// Level 1 — known-safe regenerable artifact patterns (PRD section 6)
// -----------------------------------------------------------------------------

var safeDirNames = map[string]bool{
	"node_modules": true, // regenerated by npm/pnpm/yarn
	"__pycache__":  true, // regenerated by Python
	"dist":         true, // build output
	"build":        true,
	"out":          true, // Next.js alternate output
	"target":       true, // Rust/cargo build output
	".turbo":       true,
	".cache":       true,
	"overlay2":     true, // Docker image layers
	"containers":   true, // Docker windows-containers layers
}

// safeRelativePaths match cleaned-path suffixes (case-insensitive),
// e.g. `<project>\.next\cache`.
var safeRelativePaths = []string{
	`.next\cache`,
	`.parcel-cache`,
	`.npm\_cacache`,
	`\pnpm-cache`,
	`.pnpm-store`,
	`.yarn\cache`,
	`appdata\local\pip\cache`,
	`appdata\local\npm-cache`,
	`appdata\local\pnpm-cache`,
}

// -----------------------------------------------------------------------------
// Level 2 — needs review (PRD section 6)
// -----------------------------------------------------------------------------

var reviewDirNames = map[string]bool{
	".vs":         true, // Visual Studio cache/indexes
	".idea":       true, // JetBrains indexes
	".gradle":     true,
	".svelte-kit": true,
	".nuxt":       true,
	".vite":       true,
}

var reviewFileGlobs = []string{
	"*.tsbuildinfo",
	".eslintcache",
}

// reviewOldDays - PRD: large items untouched >90 days escalate to Level 2.
const reviewOldDays = 90 * 24 * time.Hour

// Classify determines the Level for an absolute path.
//
// Order is deliberate:
//  1. Level 3 checks run FIRST and always win — fail closed toward safety.
//  2. Level 1 known-safe artifacts.
//  3. Level 2 review candidates.
//  4. Default: unclassified (0) — the UI must offer no action for it.
//
// modTime may be zero-time when unknown.
func Classify(absPath string, sizeBytes int64, modTime time.Time) (Level, string) {
	p := strings.ToLower(filepath.Clean(absPath))
	if !filepath.IsAbs(p) {
		return LevelLocked, "non-absolute paths cannot be actionable"
	}

	// ---- Level 3: hardcoded blocklist, checked FIRST, never bypassable ----
	for _, prefix := range lockedPrefixes {
		if p == prefix || strings.HasPrefix(p, prefix+`\`) {
			return LevelLocked, "under protected Windows system path"
		}
	}
	for _, part := range strings.Split(p, `\`) {
		for _, name := range lockedNames {
			if part == name {
				return LevelLocked, "protected system component"
			}
		}
	}

	base := strings.ToLower(filepath.Base(p))

	// ---- Level 1: regenerable dev artifacts ----
	if safeDirNames[base] {
		return LevelSafe, "regenerated automatically by the toolchain — safe to remove"
	}
	for _, suffix := range safeRelativePaths {
		if strings.HasSuffix(p, suffix) {
			return LevelSafe, "package-manager or bundler cache — safe to remove"
		}
	}

	// ---- Level 2: needs human review ----
	if reviewDirNames[base] {
		return LevelReview, "IDE/tool cache — verify contents before removing"
	}
	for _, glob := range reviewFileGlobs {
		if ok, _ := filepath.Match(glob, base); ok {
			return LevelReview, "stale toolchain artifact — verify before removing"
		}
	}
	// Large files (>100 MB) untouched >90 days inside a downloads-like folder.
	if !modTime.IsZero() && sizeBytes > 100*1024*1024 && time.Since(modTime) > reviewOldDays {
		parent := strings.ToLower(filepath.Base(filepath.Dir(p)))
		if parent == "downloads" {
			return LevelReview, "large download untouched for more than 90 days"
		}
	}

	return 0, "" // unclassified — no action offered
}