// Dev Clutter view — REAL scanned rebuildable artifacts.

import 'package:flutter/cupertino.dart';
import 'package:macos_ui/macos_ui.dart';

import 'app_state.dart';
import 'confirm.dart';
import 'data.dart';

class DevClutterView extends StatelessWidget {
  const DevClutterView({super.key, required this.scrollController});

  final ScrollController scrollController;

  @override
  Widget build(BuildContext context) {
    final typography = MacosTheme.of(context).typography;

    return ListView(
      controller: scrollController,
      padding: const EdgeInsets.fromLTRB(24, 24, 24, 32),
      children: [
        Text('Dev Clutter', style: typography.title2),
        const SizedBox(height: 2),
        Text(
          'Rebuildable artifacts found on this PC — cleaning is safe',
          style: typography.body.copyWith(color: CupertinoColors.systemGrey),
        ),

        const SizedBox(height: 24),

        const _SectionLabel('REBUILDABLE ARTIFACTS'),
        const SizedBox(height: 8),
        ListenableBuilder(
          listenable: appState,
          builder: (context, _) {
            if (appState.scanning) {
              return const Padding(
                padding: EdgeInsets.symmetric(vertical: 12),
                child: Row(
                  children: [
                    CupertinoActivityIndicator(),
                    SizedBox(width: 8),
                    Text('Scanning…'),
                  ],
                ),
              );
            }
            if (appState.devClutterItems.isEmpty) {
              return const Padding(
                padding: EdgeInsets.symmetric(vertical: 12),
                child: Text(
                  'No dev artifacts found. Searched C:\\Projects, '
                  'C:\\code, C:\\src, C:\\dev, C:\\work.',
                ),
              );
            }
            return Column(
              children: [
                for (final item in appState.devClutterItems)
                  _ClutterRow(item: item),
              ],
            );
          },
        ),
      ],
    );
  }
}

class _SectionLabel extends StatelessWidget {
  const _SectionLabel(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: MacosTheme.of(context).typography.caption1.copyWith(
            letterSpacing: 1.4,
            fontWeight: FontWeight.w600,
            color: CupertinoColors.systemGrey,
          ),
    );
  }
}

class _ClutterRow extends StatelessWidget {
  const _ClutterRow({required this.item});

  final CleanupItem item;

  Future<void> _clean(BuildContext context) async {
    final confirmed = await confirmAction(
      context,
      title: 'Move to Recycle Bin?',
      message:
          '${item.name} (${item.size}) is rebuildable — it can be '
          'regenerated by your tools. It will be moved to the Recycle Bin.',
      confirmLabel: 'Clean',
      confirmColor: kGreen,
    );
    if (confirmed) await appState.clean(item);
  }

  @override
  Widget build(BuildContext context) {
    final typography = MacosTheme.of(context).typography;

    return Container(
      decoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: kGrayLight)),
      ),
      child: Row(
        children: [
          Container(
            width: 8,
            height: 8,
            margin: const EdgeInsets.only(right: 12),
            decoration: const BoxDecoration(
              color: kGreen,
              shape: BoxShape.circle,
            ),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(item.name, style: typography.body),
                  const SizedBox(height: 2),
                  Text(
                    item.path,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: typography.caption1.copyWith(
                      color: CupertinoColors.systemGrey,
                    ),
                  ),
                ],
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              item.size,
              style: typography.body.copyWith(
                color: CupertinoColors.systemGrey,
                fontFeatures: const [FontFeature.tabularFigures()],
              ),
            ),
          ),
          PushButton(
            controlSize: ControlSize.small,
            color: kGreen,
            onPressed: () => _clean(context),
            child: Text(
              'Clean',
              style: typography.caption1.copyWith(
                color: CupertinoColors.white,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

